/**
 * Shared update lock management
 * Provides atomic locking mechanism for rating updates
 */

import UpdateLog from '../models/UpdateLog.js';

// Fixed ID for the global update lock document
export const LOCK_ID = 'GLOBAL_UPDATE_LOCK';

// Stale update timeout (30 minutes)
export const STALE_UPDATE_TIMEOUT_MS = 30 * 60 * 1000;

/**
 * Creates a unique owner identifier for the current process.
 * @param {string} [prefix] - Optional prefix to namespace the identifier (e.g., 'cron', 'api').
 * @returns {string} The identifier string in the form `[prefix-]pid-timestamp-randomSuffix`.
 */
export function generateOwnerId(prefix = '') {
  const pid = process.pid;
  const timestamp = Date.now();
  const random = Math.random().toString(36).substr(2, 9);
  
  return prefix 
    ? `${prefix}-${pid}-${timestamp}-${random}`
    : `${pid}-${timestamp}-${random}`;
}

/**
 * Acquire the global update lock atomically.
 *
 * Attempts to set the global lock to a running state for the provided owner.
 * If the lock is obtained, the returned object contains the updated lock document;
 * if another process holds the lock, the returned object contains the existing lock document.
 *
 * @param {string} owner - Owner identifier for the lock (e.g., generated by generateOwnerId).
 * @returns {{ success: boolean, lock?: import('../models/UpdateLog.js').default, existingLock?: import('../models/UpdateLog.js').default }}
 *   - When `success` is `true`, `lock` is the reserved UpdateLog document.
 *   - When `success` is `false`, `existingLock` is the current UpdateLog document held by another process.
 */
export async function acquireUpdateLock(owner) {
  const now = new Date();
  
  try {
    // Atomically try to acquire the lock by updating a document with fixed ID
    // Only succeeds if the document doesn't exist OR status is not 'running'
    const lock = await UpdateLog.findOneAndUpdate(
      {
        _id: LOCK_ID,
        status: { $ne: 'running' } // Only acquire if not already running
      },
      {
        $set: {
          _id: LOCK_ID,
          startedAt: now,
          status: 'running',
          owner: owner,
          usersUpdated: 0,
          completedAt: null,
          errors: []
        }
      },
      {
        upsert: true,
        new: true, // Return the updated document
        setDefaultsOnInsert: true
      }
    );
    
    if (lock) {
      // Successfully acquired lock
      return { success: true, lock };
    }
    
    // Failed to acquire - lock is held by another process
    const existingLock = await UpdateLog.findById(LOCK_ID);
    return { success: false, existingLock };
  } catch (error) {
    // If error is duplicate key (E11000), another process acquired the lock
    if (error.code === 11000) {
      const existingLock = await UpdateLog.findById(LOCK_ID);
      return { success: false, existingLock };
    }
    throw error;
  }
}

/**
 * Mark the global update lock with a final status, set completion time, apply optional updates, and clear its owner.
 * @param {string} status - Final status to set on the lock (e.g., 'completed' or 'failed').
 * @param {object} updates - Additional fields to merge into the lock document.
 */
export async function releaseUpdateLock(status, updates = {}) {
  await UpdateLog.findByIdAndUpdate(
    LOCK_ID,
    {
      $set: {
        status,
        completedAt: new Date(),
        ...updates
      },
      $unset: {
        owner: '' // Clear owner on release
      }
    }
  );
}
