/**
 * Authentication Rate Limiter
 * Tracks failed authentication attempts by IP and username
 * 
 * Uses Redis for distributed deployments (when REDIS_URL is set),
 * otherwise falls back to in-memory store for development.
 */

import { getRedisClient, isRedisEnabled } from '../config/redisStore.js';

// In-memory store for failed attempts (fallback when Redis is not available)
// Structure: { key: { count: number, resetAt: Date, lockedUntil: Date } }
const failedAttemptsStore = new Map();

// Configuration
const MAX_FAILED_ATTEMPTS = 5; // Maximum failed attempts before lockout
const LOCKOUT_DURATION_MS = 15 * 60 * 1000; // 15 minutes lockout
const WINDOW_MS = 15 * 60 * 1000; // 15 minutes window for counting attempts
const CLEANUP_INTERVAL_MS = 60 * 60 * 1000; // Cleanup expired entries every hour

/**
 * Create a storage key that uniquely identifies failed authentication attempts for an IP and username.
 * @param {string} ip - Client IP address.
 * @param {string} username - Username used during the authentication attempt.
 * @returns {string} A string key in the format `auth:<ip>:<username>` suitable for use in the in-memory store or Redis.
 */
function generateKey(ip, username) {
  // Track by both IP and username for better security
  return `auth:${ip}:${username}`;
}

/**
 * Determine the client's IP address from an Express request.
 * @param {object} req - Express request object.
 * @returns {string} The client's IP address, or `'unknown'` if it cannot be determined.
 */
function getClientIP(req) {
  return req.ip || 
         req.connection?.remoteAddress || 
         req.socket?.remoteAddress ||
         (req.headers['x-forwarded-for']?.split(',')[0]?.trim()) ||
         'unknown';
}

/**
 * Remove entries whose tracking window and any lockout have both expired.
 *
 * Iterates the in-memory failed attempts store and deletes keys where `resetAt` is earlier than the current time
 * and `lockedUntil` is either not set or earlier than the current time.
 */
function cleanupExpiredEntries() {
  const now = Date.now();
  for (const [key, data] of failedAttemptsStore.entries()) {
    // Remove if both resetAt and lockedUntil have passed
    if (data.resetAt < now && (!data.lockedUntil || data.lockedUntil < now)) {
      failedAttemptsStore.delete(key);
    }
  }
}

// Start cleanup interval and store the interval ID for graceful shutdown
let cleanupInterval = setInterval(cleanupExpiredEntries, CLEANUP_INTERVAL_MS);

/**
 * Stop the periodic cleanup interval used to remove expired in-memory entries.
 *
 * This clears the internal interval timer if running and prevents further automatic cleanup.
 */
export function stopCleanup() {
  if (cleanupInterval) {
    clearInterval(cleanupInterval);
    cleanupInterval = null;
    console.log('Auth rate limiter cleanup interval stopped');
  }
}

/**
 * Determines whether the identity represented by `key` is currently blocked due to prior failed authentication attempts.
 * @param {string} key - The storage key used to track attempts (e.g. generated by `generateKey(ip, username)`).
 * @returns {{blocked: boolean, reason?: string, retryAfter?: number}} An object where `blocked` is `true` if the identity is blocked; `reason` provides a human-readable explanation when blocked; `retryAfter` is the number of seconds until the block expires when applicable.
 */
function checkAuthLimitInMemory(key) {
  const now = Date.now();
  const entry = failedAttemptsStore.get(key);

  if (!entry) {
    return { blocked: false };
  }

  // Check if account is locked
  if (entry.lockedUntil && entry.lockedUntil > now) {
    const retryAfter = Math.ceil((entry.lockedUntil - now) / 1000);
    return {
      blocked: true,
      reason: 'Too many failed authentication attempts. Account temporarily locked.',
      retryAfter
    };
  }

  // Check if window has expired
  if (entry.resetAt < now) {
    failedAttemptsStore.delete(key);
    return { blocked: false };
  }

  // Check if threshold exceeded
  if (entry.count >= MAX_FAILED_ATTEMPTS) {
    const lockedUntil = now + LOCKOUT_DURATION_MS;
    entry.lockedUntil = lockedUntil;
    failedAttemptsStore.set(key, entry);
    
    return {
      blocked: true,
      reason: 'Too many failed authentication attempts. Account temporarily locked.',
      retryAfter: Math.ceil(LOCKOUT_DURATION_MS / 1000)
    };
  }

  return { blocked: false };
}

/**
 * Determine whether the tracked authentication identity represented by `key` is currently blocked.
 *
 * @param {string} key - Composite tracking key (e.g., "auth:<ip>:<username>").
 * @param {object} redis - Redis client instance with `get`, `del`, and `setex` methods.
 * @returns {{ blocked: boolean, reason?: string, retryAfter?: number }} An object where `blocked` indicates block state; when `blocked` is `true`, `reason` explains the block and `retryAfter` gives the remaining lockout time in seconds.
 */
async function checkAuthLimitRedis(key, redis) {
  const now = Date.now();
  const data = await redis.get(key);

  if (!data) {
    return { blocked: false };
  }

  const entry = JSON.parse(data);

  // Check if account is locked
  if (entry.lockedUntil && entry.lockedUntil > now) {
    const retryAfter = Math.ceil((entry.lockedUntil - now) / 1000);
    return {
      blocked: true,
      reason: 'Too many failed authentication attempts. Account temporarily locked.',
      retryAfter
    };
  }

  // Check if window has expired
  if (entry.resetAt < now) {
    await redis.del(key);
    return { blocked: false };
  }

  // Check if threshold exceeded
  if (entry.count >= MAX_FAILED_ATTEMPTS) {
    entry.lockedUntil = now + LOCKOUT_DURATION_MS;
    const ttl = Math.ceil(LOCKOUT_DURATION_MS / 1000);
    await redis.setex(key, ttl, JSON.stringify(entry));
    
    return {
      blocked: true,
      reason: 'Too many failed authentication attempts. Account temporarily locked.',
      retryAfter: ttl
    };
  }

  return { blocked: false };
}

/**
 * Determine whether authentication attempts for the given IP and username are currently blocked.
 * @param {string} ip - Client IP address.
 * @param {string} username - Username to check.
 * @returns {{blocked: boolean, reason?: string, retryAfter?: number}} An object where `blocked` is true if the client should be rejected; `reason` describes why the block is in effect; `retryAfter` is the number of seconds until the block is lifted when applicable.
 */
async function checkAuthLimit(ip, username) {
  const key = generateKey(ip, username);
  const redis = getRedisClient();

  if (redis && isRedisEnabled()) {
    try {
      return await checkAuthLimitRedis(key, redis);
    } catch (error) {
      console.error('Redis error in checkAuthLimit, falling back to in-memory:', error.message);
    }
  }

  return checkAuthLimitInMemory(key);
}

/**
 * Record a failed authentication attempt for the given tracking key in the in-memory store.
 *
 * If an existing, non-expired entry exists the function increments its count; otherwise it creates
 * a new entry with count = 1, a reset deadline WINDOW_MS milliseconds from now, and no lock.
 * @param {string} key - Tracking key in the form `auth:<ip>:<username>`.
 */
function recordFailedAttemptInMemory(key) {
  const now = Date.now();
  const entry = failedAttemptsStore.get(key);

  if (entry && entry.resetAt > now) {
    entry.count += 1;
  } else {
    failedAttemptsStore.set(key, {
      count: 1,
      resetAt: now + WINDOW_MS,
      lockedUntil: null
    });
  }
}

/**
 * Increment or initialize the failed-authentication counter for a given Redis key and persist it with an appropriate TTL.
 *
 * If an existing entry's window (resetAt) is still active, increments its count; otherwise resets count to 1 and starts a new window. Preserves any active lockout by using the later of `resetAt` and `lockedUntil` to compute the TTL stored in Redis.
 * @param {string} key - Redis key identifying the client (e.g., "auth:<ip>:<username>").
 * @param {{ get: Function, setex: Function }} redis - Redis client providing `get(key)` and `setex(key, ttlSeconds, value)` methods.
 */
async function recordFailedAttemptRedis(key, redis) {
  const now = Date.now();
  const data = await redis.get(key);

  let entry;
  if (data) {
    entry = JSON.parse(data);
    if (entry.resetAt > now) {
      entry.count += 1;
    } else {
      entry = { count: 1, resetAt: now + WINDOW_MS, lockedUntil: null };
    }
  } else {
    entry = { count: 1, resetAt: now + WINDOW_MS, lockedUntil: null };
  }

  // Use the maximum of resetAt and lockedUntil to preserve lockout state
  const expiresAt = entry.lockedUntil && entry.lockedUntil > entry.resetAt 
    ? entry.lockedUntil 
    : entry.resetAt;
  const ttl = Math.ceil((expiresAt - now) / 1000);
  await redis.setex(key, ttl, JSON.stringify(entry));
}

/**
 * Increment the failed-authentication counter for the given client identity.
 *
 * @param {string} ip - Client IP address used to identify the source of the attempt.
 * @param {string} username - Username involved in the failed attempt.
 */
async function recordFailedAttempt(ip, username) {
  const key = generateKey(ip, username);
  const redis = getRedisClient();

  if (redis && isRedisEnabled()) {
    try {
      await recordFailedAttemptRedis(key, redis);
      return;
    } catch (error) {
      console.error('Redis error in recordFailedAttempt, falling back to in-memory:', error.message);
    }
  }

  recordFailedAttemptInMemory(key);
}

/**
 * Remove the stored failed authentication attempts for the given client IP and username.
 * Prefers Redis when enabled; falls back to the in-memory store if Redis is unavailable or an error occurs.
 * @param {string} ip - Client IP address used to identify the attempts record.
 * @param {string} username - Username used to identify the attempts record.
 */
async function clearFailedAttempts(ip, username) {
  const key = generateKey(ip, username);
  const redis = getRedisClient();

  if (redis && isRedisEnabled()) {
    try {
      await redis.del(key);
      return;
    } catch (error) {
      console.error('Redis error in clearFailedAttempts, falling back to in-memory:', error.message);
    }
  }

  failedAttemptsStore.delete(key);
}

/**
 * Express middleware for authentication rate limiting
 */
export const authRateLimiter = async (req, res, next) => {
  const ip = getClientIP(req);
  
  // Extract username from auth header if present
  let username = 'unknown';
  try {
    const authHeader = req.headers.authorization;
    if (authHeader && authHeader.startsWith('Basic ')) {
      const base64Credentials = authHeader.split(' ')[1];
      const credentials = Buffer.from(base64Credentials, 'base64').toString('utf-8');
      const [extractedUsername] = credentials.split(':');
      if (extractedUsername) {
        username = extractedUsername;
      }
    }
  } catch (error) {
    // If we can't extract username, continue with 'unknown'
  }

  // Check if authentication should be blocked
  try {
    const limitCheck = await checkAuthLimit(ip, username);
    
    if (limitCheck.blocked) {
      return res.status(429).json({
        success: false,
        error: limitCheck.reason,
        retryAfter: limitCheck.retryAfter
      });
    }
  } catch (error) {
    console.error('Error in auth rate limiter:', error.message);
    // Continue without rate limiting on error
  }

  // Attach rate limiter functions to request for use in auth middleware
  req.authRateLimiter = {
    recordFailed: async () => await recordFailedAttempt(ip, username),
    clearFailed: async () => await clearFailedAttempts(ip, username),
    getClientIP: () => ip
  };

  next();
};

/**
 * Retrieve the current failed authentication attempts count for the given IP and username.
 * @param {string} ip - Client IP address to identify the source of attempts.
 * @param {string} username - Username associated with the attempts.
 * @returns {number} The current failed attempts count for the key, or 0 if none.
 */
export async function getFailedAttemptsCount(ip, username) {
  const key = generateKey(ip, username);
  const redis = getRedisClient();

  // Try Redis first if enabled
  if (redis && isRedisEnabled()) {
    try {
      const data = await redis.get(key);
      if (data) {
        const entry = JSON.parse(data);
        return entry.count || 0;
      }
      return 0;
    } catch (error) {
      console.error('Redis error in getFailedAttemptsCount, falling back to in-memory:', error.message);
      // Fall through to in-memory fallback
    }
  }

  // Fallback to in-memory store
  const entry = failedAttemptsStore.get(key);
  return entry ? entry.count : 0;
}

/**
 * Clear all failed attempts (for admin/testing)
 */
export function clearAllFailedAttempts() {
  failedAttemptsStore.clear();
}

// Export configuration for potential Redis migration
export const config = {
  MAX_FAILED_ATTEMPTS,
  LOCKOUT_DURATION_MS,
  WINDOW_MS
};
